apiVersion: v1
kind: BuildConfig
metadata:
  name: helloworld-nodejs
spec:
  output:
    to:
      kind: ImageStreamTag
      name: helloworld-nodejs:latest
  source:
    contextDir: /
    git:
      ref: master
      uri: https://github.com/davinryan/openshift-jenkins-nodejs-example.git
    type: Git
    secrets:
      - secret:
          name: artifactory
        destinationDir: /opt/app-root/src
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i:latest
        namespace: bnz
      incremental: false
      env:
        - name: BUILD_TARGET_DIR
          value: "build/libs"
        - name: GRADLE_USER_HOME
          value: "/opt/app-root/src"
    type: Source
  triggers:
  - type: Generic
    generic:
      secret: 41ECE3B7-A787-46FB-8C7B-BB7E53D88A23