apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: openshift-jenkins-nodejs-example
  spec:
    ports:
    - name: openshift-jenkins-nodejs-example-http
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: openshift-jenkins-nodejs-example
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: openshift-jenkins-nodejs-example
  spec:
    host: openshift-jenkins-nodejs-example
    to:
      kind: Service
      name: openshift-jenkins-nodejs-example
    port:
      targetPort: openshift-jenkins-nodejs-example-http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: openshift-jenkins-nodejs-example
  spec:
    replicas: 1
    selector:
      deploymentconfig: openshift-jenkins-nodejs-example
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: openshift-jenkins-nodejs-example
      spec:
        volumes:
        - name: config-volume
          configMap:
            name: openshift-jenkins-nodejs-example-config
            items:
              - key: application.properties
                path: application.properties
            defaultMode: 420
        containers:
        - name: openshift-jenkins-nodejs-example
          image: 172.30.1.1:5000/myproject/openshift-jenkins-nodejs-example
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 1
          name: openshift-jenkins-nodejs-example
          volumeMounts:
          - name: config-volume
            mountPath: /opt/openshift/config
          ports:
          - containerPort: 3000
            protocol: TCP
          env:
          - name: ENVIRONMENT_NAME
            value: dev
          - name: TZ
            value: Pacific/Auckland
          resources:
            limits:
              memory: 1Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
  status: {}
kind: List
metadata: {}