apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: helloworld-nodejs
  spec:
    ports:
    - name: helloworld-nodejs-http
      port: 8086
      protocol: TCP
      targetPort: 8086
    selector:
      deploymentconfig: helloworld-nodejs
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: helloworld-nodejs
  spec:
    to:
      kind: Service
      name: helloworld-nodejs
    port:
      targetPort: helloworld-nodejs-http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  status: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: helloworld-nodejs
  spec:
    replicas: 1
    selector:
      deploymentconfig: helloworld-nodejs
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: helloworld-nodejs
      spec:
        volumes:
        - name: config-volume
          configMap:
            name: helloworld-nodejs-config
            items:
              - key: application.properties
                path: application.properties
            defaultMode: 420
        containers:
        - name: helloworld-nodejs
          image: helloworld-nodejs/helloworld-nodejs
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 200
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8086
              scheme: HTTP
            initialDelaySeconds: 200
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 1
          name: helloworld-nodejs
          volumeMounts:
          - name: config-volume
            mountPath: /opt/openshift/config
          ports:
          - containerPort: 8086
            protocol: TCP
          env:
          - name: ENVIRONMENT_NAME
            value: dev
          - name: TZ
            value: Pacific/Auckland
          resources:
            limits:
              memory: 1Gi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
  status: {}
kind: List
metadata: {}