apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: Route
  metadata:
    name: openshift-jenkins-nodejs-example
  spec:
    host: openshift-jenkins-nodejs-example
    to:
      kind: Service
      name: openshift-jenkins-nodejs-example
    port:
      targetPort: openshift-jenkins-nodejs-example-http
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: jenkins
  spec:
    host: jenkins
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
      weight: 100
    wildcardPolicy: None