apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: openshift-jenkins-nodejs-example
  spec:
    ports:
    - name: openshift-jenkins-nodejs-example-http
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      deploymentconfig: openshift-jenkins-nodejs-example
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}